### PR TITLE
updating packages

### PR DESCRIPTION
**Pull request by HalcyonJAC**
**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

---

## What's included?
Describe the changes included in this pull request and highlight dependencies with other repos/tickets

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?
- Run `npm install` 
- Run `npm run serve` to make sure the app compiles and runs

## Risk - how likely is this to impact other areas?
🟠 Medium risk - this does change code that is shared with other areas

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by lloback — CHANGES_REQUESTED** [review]
Please add what needs to be tested.

Also, I did `npm install` and got

```
loback@MacBook-Pro assessments (feature/update-packages) $ npm install

> assessment-uploader@0.16.0 preinstall
> npx npm-force-resolutions


added 1577 packages, and audited 1578 packages in 29s

51 vulnerabilities (3 low, 45 moderate, 3 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
```

Let me know if this is only addressing some minors vulberabilities.

**Comment by HalcyonJAC** [comment]
@lloback I have updated some more dependancies now so that all high priority vulnerabilities are resolved.

**Comment by lloback** [comment]
```
66 moderate severity vulnerabilities
```

We should create a ticket to fix all the vulnerabilities @mbrookeswebdev @tomlovesgithub

**Review by lloback — APPROVED** [review]
✔︎

**Comment by HalcyonJAC** [comment]
As disussed with Warren, resolving all production vulnerabilities and all high priority dev vulnerabilities is enough.

**Review by mbrookeswebdev — APPROVED** [review]

**Pull request merged**
