### PR TITLE
Chore/178 upgrade firebase lib

### LINKED ISSUE #178: Upgrade Assessments Platform to use the latest Firebase library
Following the upgrade of Admin repo, we need to upgrade the other repos to the latest version.

Useful links

https://firebase.google.com/docs/web/modular-upgrade

- [ ] [jac-kit] Upgrade Firebase SDK to latest stable version
- [ ] [admin] Upgrade Firebase SDK to latest stable version
- [ ] Refactoring Authentication functions to modular APIs
- [ ] Refactoring Firestore functions to modular APIs
- [ ] Refactoring Firestore Action
- [ ] Update Firestore Action in store/*.js files

### PR DESCRIPTION
**Pull request by KoWeiJAC**
## What's included?
Closes #178 
## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test ?
Go to the preview links (may contain open assessments):
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test66@mail.com&ref=assessments/6cqpANpd4GGL50bix2nc-1
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test55@mail.com&ref=assessments/6cqpANpd4GGL50bix2nc-2
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test666@mail.com&ref=assessments/93RSbGn5o95NAK9r2eHt-1
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test2132@mail.com&ref=assessments/93RSbGn5o95NAK9r2eHt-2
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test661@mail.com&ref=assessments/97EuSzBbKEhILjyt4hcN-1
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test2112@mail.com&ref=assessments/97EuSzBbKEhILjyt4hcN-2
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test1@mail.com&ref=assessments/ZvVJun8ed9hvFQxYpzTm-1
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test2@mail.com&ref=assessments/ZvVJun8ed9hvFQxYpzTm-2
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test3@mail.com&ref=assessments/cHreMfBJiVhCKvDILBl5-1
- https://jac-assessments-develop--pr179-chore-178-upgrade-fi-87nr2vc9.web.app/sign-in?email=test4@mail.com&ref=assessments/cHreMfBJiVhCKvDILBl5-2

Test all of the functionality of the assessment site, include but not limited to:

- Sign-in/Sign-out
- All tables
- All functionalities for creating/updating/deleting data
- All functionalities for upload/download/preview files

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes a lot of changes to shared code

## Additional context
Include screen grabs, notes etc.

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Review by warrensearle — APPROVED** [review]
👍

**Review by drieJAC — COMMENTED** [review]
There are some undefined variables when I use the preview link, see screenshot

Screenshot 2024-02-05 at 11 28 46

**Review by NormaJAC — COMMENTED** [review]
I encountered the same issue as Drie

**Review by Franceswog — COMMENTED** [review]
Can 'a' be added to this comment please? 'You can visit 'a' list of.............
image

**Review by tomlovesgithub — APPROVED** [review]

**Review by nickaddy — APPROVED** [review]
Everything I was able to test worked as expected.

**Pull request merged**
