### PR TITLE
174-upgrade to vite + vue3

### LINKED ISSUE #174: Upgrade to VueJS v3
Our admin app has recently been upgraded by @drieJAC to use Vue 3 instead of Vue 2.

Lessons learned and some useful pointers have been documented here:
https://github.com/jac-uk/admin/blob/main/VUE3_UPGRADE.md

Please upgrade our Assessments app to use Vue 3 instead of Vue 2.

**Estimate:**
Large (5-10 days)

**Note**: 
 - Refer to the upgrade notes (and source code) in Admin for any help
 - @tomlovesgithub will be upgrading Assessments app and @halcyonJAC will be upgrading Apply so please do talk to each other and co-ordinate efforts if you like
 - @drieJAC is also available to help answer any questions or advise on best path forwards

### PR DESCRIPTION
**Pull request by tomlovesgithub**
## What's included?
Closes #174  

## Who should test?
✅ Product owner
✅ Developers
✅ UTG

## How to test?

For internal testing please add issues/bugs you find as comments below.

#### Sign in
- Go to one of the following urls in assessments:
- https://jac-assessments-develop--pr175-174-vue-3-upgrade-31a35ik8.web.app/sign-in?email=janedoe@test.com&ref=assessments/XpKBzFbjiVwJI38h5IaQ-1
- https://jac-assessments-develop--pr175-174-vue-3-upgrade-31a35ik8.web.app/sign-in?email=johndoe@test.com&ref=assessments/XpKBzFbjiVwJI38h5IaQ-1

#### Accept IA
- upload and submit an IA, ensure everything works as expected

#### Decline IA
- Decline and give a reason, ensure everything works as expected

#### Your Assessments
- Go to "View all Assessments" page
- Check if the information shows correctly
- Check if you can access each tab

## Risk - how likely is this to impact other areas?
🔴 High risk - this includes a lot of changes to shared code

PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

### CODE REVIEW

**Comment by tomlovesgithub** [comment]
This was failing UT due to a data issue, will be tested in the next possible upcoming live exercise

**Comment by nickaddy** [comment]
@tomlovesgithub Can you replace with Warren Omar as an approver as he won't be back until December?

**Review by warrensearle — CHANGES_REQUESTED** [review]
Code looks good to me 👍 

However the Sign Out button appears to have moved (it should be on the right rather than in the middle):

image

**Comment by NormaJAC** [comment]
I declined IA, unable to save and continue.

**Comment by warrensearle** [comment]
@tomlovesgithub @drieJAC I think this needs a data refresh for the example assessments and perhaps a couple more added to test different scenarios.... @NormaJAC is in testing mode and on fire! 🔥

**Review by warrensearle — APPROVED** [review]
Thanks for fixing the Sign Out button @tomlovesgithub the code looks good now 👍 

(just some example data for @NormaJAC to test with needed now but that's outside of code)

**Review by drieJAC — APPROVED** [review]

**Pull request merged**
