### PR TITLE
#1531 firebase app check

### PR DESCRIPTION
**Pull request by HalcyonJAC**
## What's included?
This change imports the firebase app check into the admin repository and works around an issue with the application not building on some machines or environments.

## Who should test?

✅ Developers

## How to test?
Add the public recaptcha key below into your .env.develop.local file and make some requests. Ensure that these show in the verified requests on the firebase project settings => app check in the firebase console.

`6LcVn5kbAAAAADZNrAZCfEJ2KOCyS--Alb7eHvXG`

## Risk - how likely is this to impact other areas?

🟠 Medium risk - this does change code that is shared with other areas *however* enforcement isn't enabled for form requests and firebase functions/firestore changes as yet.

## Additional context

---
PREVIEW:DEVELOP

This work can only be previewed on localhost as of now.

### CODE REVIEW

**Comment by HalcyonJAC** [comment]
I have updated the recaptcha token, added an `RECAPTCHA_TOKEN` environment variable to the GitHub project and added it to the GitHub deployment scripts

**Review by warrensearle — CHANGES_REQUESTED** [review]
@HalcyonJAC to resolve merge conflicts

**Comment by HalcyonJAC** [comment]
@warrensearle Might I ask what **node and npm version** did you use in this commit [Update firebase depency and import statement](https://github.com/jac-uk/assessments/commit/f53d1dd499437ae29576459f36be76a8621fd80c)? I found that "**lockfileVersion**" in **package-lock.json** changed from 1 to **2** which was supported by npm v7.

**Review by warrensearle — APPROVED** [review]
Looks good 👍

**Review by tomlovesgithub — APPROVED** [review]

**Pull request merged**
